spring:
  profiles: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb.skala-env:3306/CLOUD}
    username: ${SPRING_DATASOURCE_USERNAME:cloud}
    password: ${SPRING_DATASOURCE_PASSWORD:Skala25a!23$}
    driver-class-name: org.mariadb.jdbc.Driver

server:
  port: ${SERVER_PORT:8080}

management:
  server:
    port: ${MANAGEMENT_PORT:8081}