spring:
  application:
    name: ${SPRING_APP_NAME:walktogether}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  servlet:
    context-path: /
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  server:
    port: ${MANAGEMENT_PORT:8081}

  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      groups:
        readiness:
          include: "*"
        startup:
          include: "startup"

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
