apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk015-tls-ingress
  namespace: skala-practice
  annotations:
    kubernetes.io/ingress.class: public-nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: public-nginx
  tls:
  - hosts:
    - sk015-walktogether.project.skala-ai.com
    secretName: sk015-ingress-tls-secret
  rules:
  - host: sk015-walktogether.project.skala-ai.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: walktogether
            port:
              number: 8080

      - path: /walktogether
        pathType: Prefix
        backend:
          service:
            name: walktogether
            port:
              number: 8080

      - path: /actuator
        pathType: Prefix
        backend:
          service:
            name: walktogether
            port:
              number: 8081

      - path: /swagger-ui.html
            pathType: Exact
            backend:
              service:
                name: walktogether
                port:
                  number: 8080
                  
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: walktogether
            port:
              number: 8080
  # tls:
  # - hosts:
  #   - sk015-walktogether.project.skala-ai.com
  #   secretName: sk015-cm-auto-tls-secret
